<%@ Page Language="C#" validateRequest="false" AutoEventWireup="true" CodeFile="EscribirArticulo.aspx.cs" Inherits="TheCoffeePlace.Views.EscribirArticulo"  MasterPageFile="~/MasterPageTCP.master" %>
<%@ Register TagPrefix="FTB" Namespace="FreeTextBoxControls" Assembly="FreeTextBox" %>

<asp:content runat="server" ContentPlaceHolderID ="pageHead">
    
    <title> Escribir artículo</title>
	<link rel="stylesheet" type="text/css" href="CssStyle/EscribirArticuloCSS.css">

</asp:content>


<asp:content runat="server" ContentPlaceHolderID ="pageContent">

    <form id="form" runat="server">
		<ul id="escritor">
            <li>
                <asp:label ID="lblUsername" runat="server" text="Manuelito01"></asp:label>

				<p>Título</p>
				<asp:TextBox ID="txtTituloArticulo" runat="server" CssClass="titulo"></asp:TextBox>

				<p>Resumen</p>
				<asp:TextBox ID="txtResumen" runat="server" TextMode="MultiLine" CssClass="resumen"></asp:TextBox>

                <div id="autores">
				<p>Autor (es)</p>
				<asp:GridView ID="gvAutor" runat="server" AutoGenerateEditButton="True" HeaderStyle-CssClass="colID" OnRowEditing="gvAutor_RowEditing" OnRowUpdating="gvAutor_RowUpdating" AutoGenerateDeleteButton="True" 
                    OnRowDeleted="gvAutor_RowDeleted" OnRowDeleting="gvAutor_RowDeleting" CssClass="grid"  AllowPaging="true" PageSize="10" OnPageIndexChanging="gvAutor_PageIndexChanging">
				</asp:GridView>
				<asp:TextBox ID="txtNuevoAutor" runat="server"></asp:TextBox>
				<asp:Button ID="btnAgregarAutor" runat="server" Text="Agregar autor" OnClick="btnAgregarAutor_Click"/>
                </div>

			<li id ="ftxtEdit">	
                <p id ="art">Artículo</p>
				<FTB:FreeTextBox ID="ftxtEditor" runat="server" ButtonSet="OfficeMac" Width="100%" Height="500px">
				</FTB:FreeTextBox>         
            </li>
            <li id="topicos">
                <p style="margin-bottom: 10px; font-size: 150%;">Tópicos</p>
				<asp:CheckBoxList ID="chkblTopicos" runat="server" CssClass="tops"></asp:CheckBoxList>
            </li>
            <li>
                <asp:Button ID="btnGuardar" runat="server" Text="Guardar" OnClick="btnGuardar_Click" CssClass="guardar"/>
            </li>
		</ul>
        
        <ul id="imagenes">
            <li>
                        <h3 style="font-size: 200%">Tabla de Imágenes</h3>
					    <p>Para subir imágenes de su computadora, escoja un archivo .jpg o .png</p>
            </li>
            <li>
					    <asp:FileUpload ID="fileupImagen" runat="server" AllowMultiple="false" accept =".jpg, .png" CssClass="fileup"/>
                        <br />
                        <asp:Label ID="lblErrorImagen" runat="server" Text="Error" Visible="false" CssClass="errfu"></asp:Label>
		    </li>
            <li>
					    <asp:Button ID="btnSubir" runat="server" Text="Subir" OnClick="btnSubir_Click" CssClass="btnSubir"/>
		    </li>
            <li>
                        
                        <p>Puede arrastrar las imágenes subidas directamente a su artículo.</p>
					    <asp:GridView ID="gridviewImagenes" runat="server" BorderColor="Black" AutoGenerateColumns="False" EmptyDataText ="No hay archivos subidos" OnRowDeleting="OnRowDeleting" 
                            DataKeysNames="idImagenPK" CssClass="gridImg" HeaderStyle-CssClass="header" AllowPaging="true" PageSize="8" OnPageIndexChanging="gridviewImagenes_PageIndexChanging">
                            <Columns>
                                <asp:BoundField DataField="idImagenPK" ItemStyle-CssClass="colID" HeaderStyle-CssClass="colID"/>
                                <asp:ImageField DataImageUrlField="rutaImagen" HeaderText="Imagen"></asp:ImageField>   
                                <asp:CommandField ShowDeleteButton="True" ButtonType="Button" ControlStyle-CssClass="btnDelete"/>
                            </Columns>
                         </asp:GridView>
		    </li>
        </ul>

   </form>

</asp:content>