<%@ Page Language="C#" AutoEventWireup="true" CodeFile="SubirArticulo.aspx.cs" Inherits="SubirArticulo"  MasterPageFile="~/MasterPageTCP.master" %>

<asp:content runat="server" ContentPlaceHolderID ="pageHead">

    <title> Subir artículo</title>
    <link rel="stylesheet" type="text/css" href="CssStyle/SubirArticuloCSS.css">

</asp:Content>


<asp:Content ContentPlaceHolderID="pageContent" Runat="Server">
    <form id="form" runat="server">
		<ul id="escritor">
            <li>
                <asp:label ID="lblUsername" runat="server" text="Manuelito01"></asp:label>

				<p>Título</p>
				<asp:TextBox ID="txtTituloArticulo" runat="server" CssClass="titulo"></asp:TextBox>

				<p>Resumen</p>
				<asp:TextBox ID="txtResumen" runat="server" TextMode="MultiLine" CssClass="resumen"></asp:TextBox>

                <div id="autores">
				    <p>Autor (es)</p>
				    <asp:GridView ID="gvAutor" runat="server" AutoGenerateEditButton="True" HeaderStyle-CssClass="colID" OnRowEditing="gvAutor_RowEditing" OnRowUpdating="gvAutor_RowUpdating" AutoGenerateDeleteButton="True" 
                        OnRowDeleted="gvAutor_RowDeleted" OnRowDeleting="gvAutor_RowDeleting" CssClass="grid"  AllowPaging="true" PageSize="10" OnPageIndexChanging="gvAutor_PageIndexChanging">
				    </asp:GridView>
				    <asp:TextBox ID="txtNuevoAutor" runat="server"></asp:TextBox>
				    <asp:Button ID="btnAgregarAutor" runat="server" Text="Agregar autor" OnClick="btnAgregarAutor_Click"/>
                </div>

			<li id="artFU">	
                <p style="font-size: 150%;">Artículo</p>
                <p>Seleccione un archivo de tipo .docx</p>
		        <asp:FileUpload ID="fuArticulo" runat="server" accept=".docx" CssClass="fuArt"/>
                <asp:Label ID="lblErrorArticulo" runat="server" Text="Error" Visible="false" CssClass="errfu"></asp:Label>
            </li>
            <li>
                <p style="margin-bottom: 10px; font-size: 150%;">Tópicos</p>
				<asp:CheckBoxList ID="chkblTopicos" runat="server" CssClass="tops"></asp:CheckBoxList>
            </li>
            <li>
                <asp:Button ID="btnGuardar" runat="server" Text="Guardar" OnClick="btnGuardar_Click" CssClass="guardar"/>
            </li>
		</ul>       
    </form>
</asp:Content>